### ISSUE TITLE
 '/tmp/chromium' Permission denied

### ISSUE THREAD

**Issue by mcbaloo** [litmus/HeadlessChromium.Puppeteer.Lambda.Dotnet#128]
Hello, i am trying to use this project with my aws Lambda  .NET 6 function. However, i get An error occurred trying to start process '/tmp/chromium' with working directory '/var/task'. Permission denied while testing. I am not sure how to solve this. Can you please provide some clarity? Here is my docker file

```
FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build

WORKDIR /app

ENV src=./ticketSvc


COPY $src/ticketSvc.csproj ./
RUN dotnet restore "ticketSvc.csproj"
COPY ["./ticketSvc", "ticketSvc"]

COPY $src .

WORKDIR "/app/ticketSvc"
RUN dotnet publish "ticketSvc.csproj" -p:PublishReadyToRun=false -c Release -o /app/out

FROM public.ecr.aws/lambda/dotnet:6


WORKDIR /var/task



COPY --from=build /app/out .

ENTRYPOINT [ "/lambda-entrypoint.sh","ticketSvc::ticketSvc.Function::FunctionHandler" ]
```

**Comment by brianfeucht** [comment]
Hi @mcbaloo 

Can you share the C# code you are using to launch chrome? 

We have a working sample application on .NET 6 you can use a reference at https://github.com/litmus/HeadlessChromium.Puppeteer.Lambda.Dotnet/tree/main/sample/SampleLambda-dotnet6

**Comment by mcbaloo** [comment]
@brianfeucht 

var loggerFactory = LoggerFactory.Create(builder => builder.AddConsole());
 var browserLauncher = new HeadlessChromiumPuppeteerLauncher(loggerFactory);
 await using var browser = await Puppeteer.LaunchAsync(new LaunchOptions
 {
     Headless = true,
    

 });
 await using (var page = await browser.NewPageAsync())
 {
     await page.SetContentAsync(html);
     var responseStream = await page.PdfDataAsync();
 }

**Comment by brianfeucht** [comment]
That looks correct.  

The process for extracting and setting up the chromium binary can be found [here](https://github.com/litmus/HeadlessChromium.Puppeteer.Lambda.Dotnet/blob/main/src/HeadlessChromium.Puppeteer.Lambda.Dotnet/ChromiumExtractor.cs#L66) and it includes setting up file permissions.

Seems like either this process is failing or something else is creating the file `/tmp/chromium` before this code is called.  Either way you should have some clues in your cloudwatch logs since you are writing to the console.

**Comment by brianfeucht** [comment]
@mcbaloo I'll need you to either provide more logs or code that reproduces the issue.  I'm not able to reproduce the issue here.
