### ISSUE TITLE
Failed to initialize WebGL

### ISSUE THREAD

**Issue by CheeseNPort** [litmus/HeadlessChromium.Puppeteer.Lambda.Dotnet#89]
I came across this project while trying to work with puppeteer sharp, on AWS lambda to render images from WebGL, specifically mapbox.

While the javascript puppeteer does this fine in Lambda, dotnet does not. The browser throw an error "Failed to initialize WebGL" when trying to load the web page with a Web GL element on.

**Comment by brianfeucht** [comment]
This may be due to swiftshader not getting put in the expected location.  We do this [here](https://github.com/litmus/HeadlessChromium.Puppeteer.Lambda.Dotnet/blob/main/src/HeadlessChromium.Puppeteer.Lambda.Dotnet/ChromiumExtractor.cs#L64)

Can you provide more details on how you reproduced this?  What Lambda runtime are you using?  What nuget package version did you use?  Do you have a sample script to reproduce the error?

**Comment by CheeseNPort** [comment]
It was using a docker image based on Net 6, however we experienced the same error when running it inside the .Net 6 runtime. We got around it in the end by creating a completely custom docker image and manually loading the dependencies in the docker startup. It was rather complicated but we no longer have the issue.
